[package]
name = "mtrx-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mtrx_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"

[dev-dependencies]
rstest = "0.17.0"
